#! /QOpenSys/pkgs/bin/bash
if [ -n "$2" ]
then
  package="$2"
else
  package="ruby-devel"
fi
cd /QOpenSys
if [ -n "$1" ]
then
  crn="$1"
else
  crn="chRootRiby"
fi
if [ -e ${crn} ]
then
  if [ -d ${crn} ]
  then
    echo First remove the directory /QOpenSys/${crn} if you really want to recreate it
  else
    echo Choose a different name for the directory: a file named ${crn} already exist in /QOpenSys
  fi  
else
  yum -y install ibmichroot
  chroot_setup -y /QOpenSys/${crn}
  yum -y --installroot=/QOpenSys/${crn} install yum ca-certificates-mozilla
  mkdir /QOpenSys/${crn}/QOpenSys/etc/yum/repos.d
  system -q -i "CPY OBJ('/QOpenSys/etc/yum/repos.d/ibm.repo') TODIR('/QOpenSys/"${crn}"/QOpenSys/etc/yum/repos.d')"
  chroot /QOpenSys/${crn} /QOpenSys/pkgs/bin/bash <<EOT
  mkdir $HOME
  chmod 0755 $HOME
  chmod +t /tmp
  yum -y install git
  cd $HOME
  git clone https://github.com/AndreaRibuoli/RIBY.git
  cp ./RIBY/andrearibuoli.repo /QOpenSys/etc/yum/repos.d
  yum -y install ${package}
  ruby -v
  exit
EOT  
fi
